import type { editor } from 'monaco-editor'

export function registerMonacoThemes(monaco: { editor: typeof editor }) {
  monaco.editor.defineTheme('flowdeck-dracula', {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '6272a4', fontStyle: 'italic' },
      { token: 'string', foreground: 'f1fa8c' },
      { token: 'keyword', foreground: 'ff79c6', fontStyle: 'bold' },
      { token: 'keyword.operator', foreground: 'ff79c6' },
      { token: 'number', foreground: 'bd93f9' },
      { token: 'type', foreground: '8be9fd' },
      { token: 'class', foreground: '8be9fd' },
      { token: 'function', foreground: '50fa7b' },
      { token: 'variable', foreground: 'f8f8f2' },
      { token: 'operator', foreground: 'ff79c6' },
      { token: 'delimiter', foreground: 'f8f8f2' },
    ],
    colors: {
      'editor.background': '#282a36',
      'editor.foreground': '#f8f8f2',
      'editor.lineHighlightBackground': '#44475a55',
      'editor.selectionBackground': '#44475a',
      'editor.inactiveSelectionBackground': '#44475a66',
      'editorCursor.foreground': '#f8f8f2',
      'editorLineNumber.foreground': '#6272a4',
      'editorLineNumber.activeForeground': '#f8f8f2',
      'editorGutter.background': '#282a36',
      'editorWidget.background': '#21222c',
      'editorWidget.border': '#44475a',
      'editorSuggestWidget.background': '#21222c',
      'editorSuggestWidget.border': '#44475a',
      'editorSuggestWidget.selectedBackground': '#44475a',
      'scrollbarSlider.background': '#44475a55',
      'scrollbarSlider.hoverBackground': '#44475a',
      'minimap.background': '#282a36',
    },
  })

  monaco.editor.defineTheme('flowdeck-monokai', {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '75715e', fontStyle: 'italic' },
      { token: 'string', foreground: 'e6db74' },
      { token: 'keyword', foreground: 'f92672', fontStyle: 'bold' },
      { token: 'keyword.operator', foreground: 'f92672' },
      { token: 'number', foreground: 'ae81ff' },
      { token: 'type', foreground: '66d9e8' },
      { token: 'class', foreground: '66d9e8' },
      { token: 'function', foreground: 'a6e22e' },
      { token: 'variable', foreground: 'f8f8f2' },
      { token: 'operator', foreground: 'f92672' },
      { token: 'delimiter', foreground: 'f8f8f2' },
    ],
    colors: {
      'editor.background': '#272822',
      'editor.foreground': '#f8f8f2',
      'editor.lineHighlightBackground': '#3e3d3255',
      'editor.selectionBackground': '#49483e',
      'editor.inactiveSelectionBackground': '#49483e66',
      'editorCursor.foreground': '#f8f8f2',
      'editorLineNumber.foreground': '#75715e',
      'editorLineNumber.activeForeground': '#f8f8f2',
      'editorGutter.background': '#272822',
      'editorWidget.background': '#1e1f1c',
      'editorWidget.border': '#4a4b3a',
      'editorSuggestWidget.background': '#1e1f1c',
      'editorSuggestWidget.border': '#4a4b3a',
      'editorSuggestWidget.selectedBackground': '#49483e',
      'scrollbarSlider.background': '#49483e55',
      'scrollbarSlider.hoverBackground': '#49483e',
      'minimap.background': '#272822',
    },
  })
}
